export const productData = {
    "company": {
        "name": "KCS CCTV CAMERAS SERVICE ENTERPRISES!",
        "tagline": "Advanced Security & IT Solutions"
    },
    "filters": {
        "categories": [
            "CCTV Cameras",
            "Wireless & Smart Cameras",
            "Recording Devices",
            "Storage Devices",
            "Cables & Accessories",
            "Power Solutions",
            "IT Services"
        ],
        "brands": [
            "HIKVISION",
            "CP-PLUS",
            "ADS VISION",
            "HONEYWELL",
            "TRUEVIEW",
            "HI-TECH",
            "PRAMA",
            "DAHUA",
            "WD",
            "Seagate",
            "WD Purple",
            "KCS",
            "Microsoft",
            "Windows"
        ]
    },
    "products": [
        {
            "id": 1,
            "productId": "KCS-001",
            "name": "2MP Dome Camera",
            "category": "CCTV Cameras",
            "company": "HIKVISION",
            "type": "Dome Cam",
            "resolution": "2 Megapixel",
            "description": "Crystal clear 2MP indoor surveillance camera with night vision.",
            "price": "₹1,500",
            "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd"
        },
        {
            "id": 2,
            "productId": "KCS-002",
            "name": "3MP Bullet Camera",
            "category": "CCTV Cameras",
            "company": "CP-PLUS",
            "type": "Bullet Cam",
            "resolution": "3 Megapixel",
            "description": "Weatherproof outdoor bullet camera with HD recording.",
            "price": "₹1,800",
            "image": "https://images.unsplash.com/photo-1558002038-1055907df827"
        },
        {
            "id": 3,
            "productId": "KCS-003",
            "name": "5MP Ultra HD Camera",
            "category": "CCTV Cameras",
            "company": "DAHUA",
            "type": "Bullet Cam",
            "resolution": "5 Megapixel",
            "description": "Ultra HD surveillance with enhanced night visibility.",
            "price": "₹2,500",
            "image": "https://cdn.shoplightspeed.com/shops/622154/files/59430091/650x650x2/dahua-hd-cvi-5mp-full-colour-bullet-camera-with-au.jpg"
        },
        {
            "id": 4,
            "productId": "KCS-004",
            "name": "8MP 4K Security Camera",
            "category": "CCTV Cameras",
            "company": "HONEYWELL",
            "type": "Dome Cam",
            "resolution": "8 Megapixel (4K)",
            "description": "Premium 4K security camera for commercial monitoring.",
            "price": "₹4,200",
            "image": "https://tse4.mm.bing.net/th/id/OIP.hvg2dT53lYP0RhYma7HZAAHaEQ?pid=Api&P=0&h=180"
        },
        {
            "id": 5,
            "productId": "KCS-005",
            "name": "4G WiFi Camera",
            "category": "Wireless & Smart Cameras",
            "company": "TRUEVIEW",
            "type": "Smart Cam",
            "resolution": "N/A",
            "description": "Remote monitoring with 4G SIM and WiFi connectivity.",
            "price": "₹3,500",
            "image": "https://tse4.mm.bing.net/th/id/OIP.5eGp5CTykD7o16WjGTLUKwHaHa?pid=Api&P=0&h=180"
        },
        {
            "id": 6,
            "productId": "KCS-006",
            "name": "360 Rotate Robo Camera",
            "category": "Wireless & Smart Cameras",
            "company": "CP-PLUS",
            "type": "PTZ Cam",
            "resolution": "N/A",
            "description": "360-degree smart tracking camera with mobile control.",
            "price": "₹2,200",
            "image": "https://tse4.mm.bing.net/th/id/OIP.57PHmXVEMsps8eNEPPTWvgAAAA?pid=Api&P=0&h=180"
        },
        {
            "id": 7,
            "productId": "KCS-007",
            "name": "Solar Security Camera",
            "category": "Wireless & Smart Cameras",
            "company": "ADS VISION",
            "type": "Solar Cam",
            "resolution": "N/A",
            "description": "Eco-friendly solar powered outdoor surveillance.",
            "price": "₹6,500",
            "image": "https://m.media-amazon.com/images/I/71u8IG9OwSL._AC_SL1500_.jpg"
        },
        {
            "id": 8,
            "productId": "KCS-008",
            "name": "Bulb Model Camera",
            "category": "Wireless & Smart Cameras",
            "company": "HI-TECH",
            "type": "Hidden Cam",
            "resolution": "N/A",
            "description": "Hidden bulb-style smart security camera with WiFi.",
            "price": "₹1,600",
            "image": "https://m.media-amazon.com/images/I/61UPf3ujCGL._AC_SL1500_.jpg"
        },
        {
            "id": 9,
            "productId": "KCS-009",
            "name": "4 Channel DVR",
            "category": "Recording Devices",
            "company": "PRAMA",
            "type": "Digital Video Recorder",
            "resolution": "Supports up to 5MP",
            "description": "Supports up to 4 CCTV channels with HD playback.",
            "price": "₹2,800",
            "image": "https://tse3.mm.bing.net/th/id/OIP.LWJvYzk_pFD_RAQsvUJeXwHaEm?pid=Api&P=0&h=180"
        },
        {
            "id": 10,
            "productId": "KCS-010",
            "name": "8 Channel DVR",
            "category": "Recording Devices",
            "company": "HIKVISION",
            "type": "Digital Video Recorder",
            "resolution": "Supports up to 5MP",
            "description": "Reliable 8CH digital video recording system.",
            "price": "₹4,200",
            "image": "https://tse1.mm.bing.net/th/id/OIP.5J2-raC5V5Mn4NAdoU--1QHaFq?pid=Api&P=0&h=180"
        },
        {
            "id": 11,
            "productId": "KCS-011",
            "name": "16 Channel DVR",
            "category": "Recording Devices",
            "company": "DAHUA",
            "type": "High End Recorder",
            "resolution": "Supports up to 8MP",
            "description": "Commercial-grade 16CH DVR with remote access.",
            "price": "₹7,500",
            "image": "https://tse2.mm.bing.net/th/id/OIP.5-E57hRaB8HmbP5eVFvBlQHaB2?pid=Api&P=0&h=180"
        },
        {
            "id": 12,
            "productId": "KCS-012",
            "name": "64 Channel DVR",
            "category": "Recording Devices",
            "company": "HONEYWELL",
            "type": "Enterprise Recorder",
            "resolution": "4K Support",
            "description": "Enterprise surveillance management solution.",
            "price": "₹28,500",
            "image": "https://www.ntc-tech.com/cdn/shop/products/bT80Z-gbZRlH8BWgx31p34UJ1-vfOPxJ93SeFrR0doolWDzZh7O6nXgJOGLUBxo3b36C-Rdk1IdMYZ5SNygg3mezFUYjO2c_s4470_5ad488ae-c399-4690-9e91-d1d18af5a405.jpg?v=1694203836&width=1946"
        },
        {
            "id": 13,
            "productId": "KCS-013",
            "name": "500GB Surveillance HDD",
            "category": "Storage Devices",
            "company": "WD",
            "type": "Hard Disk",
            "resolution": "N/A",
            "description": "Reliable surveillance storage for DVR systems.",
            "price": "₹1,200",
            "image": "https://down-id.img.susercontent.com/file/id-11134207-7r991-llp4fp16eftt77"
        },
        {
            "id": 14,
            "productId": "KCS-014",
            "name": "1TB Surveillance HDD",
            "category": "Storage Devices",
            "company": "Seagate",
            "type": "Hard Disk",
            "resolution": "N/A",
            "description": "High-performance hard disk for 24/7 recording.",
            "price": "₹2,500",
            "image": "https://cpimg.tistatic.com/08873298/b/4/1-TB-Seagate-Surveillance-HDD.jpg"
        },
        {
            "id": 15,
            "productId": "KCS-015",
            "name": "4TB Surveillance HDD",
            "category": "Storage Devices",
            "company": "WD Purple",
            "type": "Hard Disk",
            "resolution": "N/A",
            "description": "Premium storage optimized for CCTV systems.",
            "price": "₹8,500",
            "image": "https://m.media-amazon.com/images/I/71giWLo+PFL._AC_SL1500_.jpg"
        },
        {
            "id": 16,
            "productId": "KCS-016",
            "name": "CAT 6 Outdoor Cable",
            "category": "Cables & Accessories",
            "company": "KCS",
            "type": "Networking Cable",
            "resolution": "N/A",
            "description": "High-speed outdoor CAT6 networking cable.",
            "price": "₹25 / Mtr",
            "image": "https://down-ph.img.susercontent.com/file/ph-11134207-7r98s-lukb50qconyj8d"
        },
        {
            "id": 17,
            "productId": "KCS-017",
            "name": "HDMI Cable 20M",
            "category": "Cables & Accessories",
            "company": "KCS",
            "type": "Video Cable",
            "resolution": "N/A",
            "description": "Long-range HDMI cable for HD video transmission.",
            "price": "₹1,200",
            "image": "https://tse2.mm.bing.net/th/id/OIP.xzdrQVuhunDGMH_oX2-HSwHaFj?pid=Api&P=0&h=180"
        },
        {
            "id": 18,
            "productId": "KCS-018",
            "name": "BNC Cable",
            "category": "Cables & Accessories",
            "company": "KCS",
            "type": "Connector Cable",
            "resolution": "N/A",
            "description": "Premium CCTV BNC connector cable.",
            "price": "₹150",
            "image": "https://5.imimg.com/data5/SELLER/Default/2023/9/348767474/BZ/QX/QK/3980925/bnc-connector-1000x1000.jpg"
        },
        {
            "id": 19,
            "productId": "KCS-019",
            "name": "Video Balun",
            "category": "Cables & Accessories",
            "company": "KCS",
            "type": "Transmission Device",
            "resolution": "N/A",
            "description": "High-quality video transmission balun.",
            "price": "₹450 / Pair",
            "image": "https://www.7tech.com.co/wp-content/uploads/2020/03/Video-Balun-Pasivo-HD-Esencial-para-C%C3%A1maras-de-Seguridad-1.jpg"
        },
        {
            "id": 20,
            "productId": "KCS-020",
            "name": "4CH Power Supply",
            "category": "Power Solutions",
            "company": "KCS",
            "type": "SMPS",
            "resolution": "N/A",
            "description": "Stable power distribution for CCTV systems.",
            "price": "₹450",
            "image": "https://5.imimg.com/data5/SELLER/Default/2022/12/WR/GK/QL/69759081/smps-4ch-power-supply-500x500.jpg"
        },
        {
            "id": 21,
            "productId": "KCS-021",
            "name": "8CH Power Supply",
            "category": "Power Solutions",
            "company": "KCS",
            "type": "SMPS",
            "resolution": "N/A",
            "description": "Heavy-duty CCTV power supply solution.",
            "price": "₹850",
            "image": "https://tse1.mm.bing.net/th/id/OIP.YBd4ECGq1Nrdxdtq5nRauwHaJ2?pid=Api&P=0&h=180"
        },
        {
            "id": 22,
            "productId": "KCS-022",
            "name": "Adapter Power Cable",
            "category": "Power Solutions",
            "company": "KCS",
            "type": "Power Adapter",
            "resolution": "N/A",
            "description": "Durable adapter cable for camera systems.",
            "price": "₹200",
            "image": "https://tse2.mm.bing.net/th/id/OIP.7cH71vGO3I0AIagQ5IdoRAHaHa?pid=Api&P=0&h=180"
        },
        {
            "id": 23,
            "productId": "KCS-023",
            "name": "Microsoft Solutions",
            "category": "IT Services",
            "company": "Microsoft",
            "type": "Software Service",
            "resolution": "N/A",
            "description": "Licensed Microsoft software and support services.",
            "price": "Custom Quote",
            "image": "https://keysexperts.com/wp-content/uploads/2025/07/install-office-2024-pro-plus-ltsc-odt-oct-steps.jpg"
        },
        {
            "id": 24,
            "productId": "KCS-024",
            "name": "Windows Installation",
            "category": "IT Services",
            "company": "Windows",
            "type": "OS Installation",
            "resolution": "N/A",
            "description": "Professional Windows OS installation and setup.",
            "price": "₹500",
            "image": "https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/02/windows-11-installation-phase.jpg"
        }
    ]
};
